### ISSUE TITLE
Japanese symbols

### ISSUE THREAD

**Issue by BjornMelgaard** [taohex/nvim#3]
There much of japan symbols in startify menu and in statusline

**Comment by BjornMelgaard** [comment]
Is this project abandoned?

**Comment by taohex** [comment]
Hi @BjornMelgaard , could you please add a screenshot?
Thanks!

**Comment by BjornMelgaard** [comment]
yep, something like this, from gnome-terminal)
![13-12 00 37](https://cloud.githubusercontent.com/assets/7573215/21135916/14e7db5c-c12c-11e6-8841-b54bf920921c.png)

**Comment by BjornMelgaard** [comment]
And currently nvim support seamlessly [this two themes](https://github.com/neovim/neovim/wiki/Following-HEAD#20160204)
And for neovim-qt  you must put all gui code in `ginit.vim` by the way

**Comment by taohex** [comment]
OK. Thanks for the informations!

**Comment by taohex** [comment]
Hi @BjornMelgaard ,

It's not Japanese symbols. It's [nerd-fonts](https://github.com/ryanoasis/nerd-fonts). Something like this:

![screen shot 2016-12-19 at 11 48 29 am](https://cloud.githubusercontent.com/assets/1678003/21300721/913abada-c5e1-11e6-9956-be360230ea7a.png)

I have updated the project to turn off this feature by default. If you want to turn on it, config your environment to support [nerd-fonts](https://github.com/ryanoasis/nerd-fonts). Then `let g:nvim_settings.nerd_fonts = 1` in `init.vim`.

**Comment by BjornMelgaard** [comment]
Oh, thanks)
